# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: l_hand
  joint_model_group_pose: namste
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - l1_joint
    - l2_joint
    - l3_joint
    - l4_joint
    - l5_joint
    - r1_joint
    - first_joint
    - second_joint
    - third_joint
    - 4th_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: l_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l1_joint
      - l2_joint
      - l3_joint
      - l4_joint
      - l5_joint
  - name: r_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r1_joint
      - first_joint
      - second_joint
      - third_joint
      - 4th_joint