# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_hand
  joint_model_group_pose: pose_l_1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - head_joint
    - left_sholder
    - laj_1
    - laj_2
    - laj_3
    - laj_4
    - right_sholder
    - raj_1
    - raj_2
    - raj_3
    - raj_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_sholder
      - laj_1
      - laj_2
      - laj_3
      - laj_4
controller:
  type: effort_controllers/JointPositionController
  joints:
    []
  gains:
    {}
# joint1_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: right_sholder
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint2_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: left_sholder
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint3_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: head_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint4_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: laj_1
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint5_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: laj_2
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint6_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: laj_3
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint7_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: laj_4
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint8_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: raj_1
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint9_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: raj_2
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint10_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: raj_3
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint11_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: raj_4
#   pid: {p: 100.0, i: 0.01, d: 10.0}