# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_hand
  joint_model_group_pose: l_pose_1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - head_joint
    - left_sholder
    - laj_1
    - laj_2
    - laj_3
    - gripper_joint
    - finger_joint_1
    - finger_joint_2
    - right_sholder
    - raj_1
    - raj_2
    - raj_3
    - raj_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []